name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  lint:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - name: Run rustfmt
        run: cargo fmt --all --check

  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@master

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: swatinem/rust-cache@v2

      - name: "Display network interfaces on machine (for test failure debugging)"
        run: cargo run --example list_interfaces

      - name: Run cargo build
        run: cargo build

      - name: Run cargo test
        run: cargo test

  cross:
    name: Cross compile
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-musl
          - armv7-linux-androideabi
          - aarch64-linux-android
          - x86_64-unknown-freebsd
          - x86_64-unknown-netbsd

    steps:
      - uses: actions/checkout@master

      - name: Install Rust Toolchain
        run: rustup toolchain install stable --profile minimal --no-self-update

      - uses: swatinem/rust-cache@v2

      - name: Install cross
        run: cargo install cross

      - name: Cross Compile Check
        run: |
          export CARGO_TARGET_DIR=target/build/${{ matrix.target }}
          cross check --target ${{ matrix.target }}
